Traceback (most recent call last):
  File "C:\Users\aaron\CODING\SCAI\train.py", line 21, in <module>
    x = tf.keras.layers.MaxPooling2D((2,2))(x)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\framework\ops.py", line 1963, in _create_c_op
    raise ValueError(e.message)
ValueError: Exception encountered when calling layer "max_pooling2d_1" (type MaxPooling2D).
Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 2, 2, 1], padding="VALID", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,5,1,24].
Call arguments received by layer "max_pooling2d_1" (type MaxPooling2D):
  â€¢ inputs=tf.Tensor(shape=(None, 5, 1, 24), dtype=float32)