Traceback (most recent call last):
  File "C:\Users\aaron\CODING\SCAI\train.py", line 20, in <module>
    x = tf.keras.layers.Conv2D(wandb.config.conv2_filters, wandb.config.conv2_kernelsize, activation=wandb.config.activation_2)(x)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\layers\convolutional\base_conv.py", line 307, in compute_output_shape
    raise ValueError(
ValueError: One of the dimensions in the output is <= 0 due to downsampling in conv2d_1. Consider increasing the input size. Received input shape [None, 7, 3, 5] which would produce output shape with a zero or negative value in a dimension.