Traceback (most recent call last):
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_config.py", line 166, in __getattr__
    return self.__getitem__(key)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_config.py", line 133, in __getitem__
    return self._items[key]
KeyError: 'decay_steps'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\aaron\CODING\SCAI\train.py", line 31, in <module>
    decay_steps=wandb.config.decay_steps,  # number of epochs over which to decay the learning rate
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_config.py", line 168, in __getattr__
    raise AttributeError(
AttributeError: '<class 'wandb.sdk.wandb_config.Config'>' object has no attribute 'decay_steps'